//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.12 at 06:51:44 PM PDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://springws.example.com/ws/user-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package stubs.com.example.springws.ws.user_service;
